# Generated by Django 2.2.2 on 2019-09-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='keywords', max_length=255, null=True, verbose_name='关键字(seo)'),
        ),
        migrations.AlterField(
            model_name='compose',
            name='title',
            field=models.CharField(blank=True, default='', help_text='title', max_length=255, null=True, verbose_name='标题(seo)'),
        ),
    ]
