# Generated by Django 2.2.2 on 2019-08-25 12:19

import DjangoUeditor.models
from django.db import migrations, models
import quanbenxiaoshuo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='标题')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('image', models.ImageField(blank=True, null=True, storage=quanbenxiaoshuo.storage.ImageStorage(), upload_to='novel/%Y/%m', verbose_name='小说封面')),
                ('info', DjangoUeditor.models.UEditorField(default='', verbose_name='简介')),
                ('title', models.CharField(default='', help_text='title', max_length=255, verbose_name='标题(seo)')),
                ('keywords', models.CharField(default='', help_text='keywords', max_length=255, verbose_name='关键字(seo)')),
                ('description', models.CharField(default='', help_text='description', max_length=255, verbose_name='描述(seo)')),
                ('status', models.CharField(choices=[('D', '不公开'), ('P', '公开')], default='D', max_length=1, verbose_name='状态')),
                ('slug', models.SlugField(blank=True, default='', max_length=80, unique=True, verbose_name='(URL)别名')),
                ('is_full', models.BooleanField(default=False, verbose_name='是否完本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('album', models.ManyToManyField(blank=True, related_name='novel_album', to='albums.Album', verbose_name='专辑')),
                ('category', models.ManyToManyField(blank=True, related_name='novel_category', to='albums.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'ordering': ('-updated_at',),
                'unique_together': {('name', 'author')},
            },
        ),
    ]
