# Generated by Django 2.2.2 on 2019-08-25 20:18

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('novels', '0002_auto_20190825_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='多个标签使用,(英文)隔开', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='小说类型'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分卷名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_section', to='novels.Novel', verbose_name='小说')),
            ],
            options={
                'verbose_name': '分卷名',
                'verbose_name_plural': '分卷名',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分卷名')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_chapter', to='novels.Section', verbose_name='分卷名')),
            ],
            options={
                'verbose_name': '章节名',
                'verbose_name_plural': '章节名',
                'ordering': ('order',),
            },
        ),
    ]
