# Generated by Django 2.2.2 on 2019-08-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20190825_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='novel_chapter', to='novels.Novel', verbose_name='小说'),
        ),
    ]
