# Generated by Django 2.2.2 on 2019-08-26 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_chapter_novel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='章节名'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, help_text='不写自动递增', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='(URL)别名'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_content', to='novels.Chapter', verbose_name='章节')),
                ('novel', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='novel_content', to='novels.Novel', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
    ]
