# Generated by Django 2.2.2 on 2019-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_auto_20190831_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='info',
            field=models.TextField(verbose_name='简介'),
        ),
    ]
