# Generated by Django 2.2.2 on 2019-08-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_auto_20190826_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('order',), 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='section',
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='novels.Chapter', verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='novel_chapter', to='novels.Novel', verbose_name='小说名称'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
