# Generated by Django 2.2.2 on 2019-08-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_auto_20190826_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='parent_category',
        ),
    ]
