# Generated by Django 2.2.2 on 2019-09-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_auto_20190831_1708'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='chapter',
            index_together={('novel', 'id'), ('novel', 'order')},
        ),
    ]
