# Generated by Django 2.2.2 on 2019-09-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_auto_20190901_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='push',
            field=models.BooleanField(default=False, help_text='是否已经推送给熊掌', verbose_name='推送'),
        ),
    ]
