# Generated by Django 2.2.2 on 2019-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_remove_chapter_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='insert',
            field=models.SmallIntegerField(blank=True, default=0, help_text='插入章节order', null=True, verbose_name='插入章节'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, help_text='自动递增', verbose_name='排序'),
        ),
    ]
