# Generated by Django 2.2.2 on 2019-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_auto_20190826_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_tab',
            field=models.BooleanField(default=False, help_text='是否目录', verbose_name='是否目录'),
        ),
    ]
