# Generated by Django 2.2.2 on 2019-09-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_chapter_push'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='chapter',
            index_together={('novel', 'id', 'is_tab'), ('novel', 'order', 'is_tab')},
        ),
    ]
