# Generated by Django 2.2.2 on 2019-09-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_auto_20190902_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='(URL)别名'),
        ),
        migrations.AlterIndexTogether(
            name='chapter',
            index_together={('novel', 'order', 'is_tab'), ('novel', 'slug', 'is_tab')},
        ),
    ]
