# Generated by Django 2.2.2 on 2019-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_chapter_is_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='novel',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_tab',
            field=models.BooleanField(default=False, verbose_name='是否目录'),
        ),
    ]
