# Generated by Django 2.2.2 on 2019-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_auto_20190902_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='keywords', max_length=255, null=True, verbose_name='关键字(seo)'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(blank=True, default='', help_text='title', max_length=255, null=True, verbose_name='标题(seo)'),
        ),
    ]
