# Generated by Django 2.2.2 on 2019-08-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_auto_20190826_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('D', '不公开'), ('P', '公开')], db_index=True, default='D', max_length=1, verbose_name='状态'),
        ),
    ]
