# Generated by Django 2.2.2 on 2019-08-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0011_auto_20190828_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, help_text='自动递增', verbose_name='排序'),
        ),
        migrations.AlterIndexTogether(
            name='novel',
            index_together={('status', 'slug')},
        ),
    ]
