# Generated by Django 2.2.2 on 2019-08-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_auto_20190828_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, related_name='album_novel', to='albums.Album', verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_novel', to='albums.Category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('D', '不公开'), ('P', '公开')], default='D', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterIndexTogether(
            name='chapter',
            index_together={('novel', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='content',
            index_together={('chapter', 'id')},
        ),
    ]
