# Generated by Django 2.2.2 on 2019-08-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_auto_20190828_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='album_novel', to='albums.Album', verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_novel', to='albums.Category', verbose_name='类别'),
        ),
    ]
