# Generated by Django 2.2.2 on 2019-08-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0015_auto_20190829_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='novels.Content', verbose_name='内容'),
        ),
    ]
