# Generated by Django 2.2.2 on 2019-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0016_auto_20190829_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default='', verbose_name='小说内容'),
        ),
    ]
