# Generated by Django 2.2.2 on 2019-08-30 05:52

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import quanbenxiaoshuo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, unique=True, verbose_name='类别名')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='(URL)别名')),
                ('title', models.CharField(default='', help_text='title', max_length=255, verbose_name='标题(seo)')),
                ('keywords', models.CharField(default='', help_text='keywords', max_length=255, verbose_name='关键字(seo)')),
                ('description', models.CharField(default='', help_text='description', max_length=255, verbose_name='描述(seo)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, storage=quanbenxiaoshuo.storage.ImageStorage(), upload_to='album/%Y/%m', verbose_name='专辑封面')),
                ('info', DjangoUeditor.models.UEditorField(default='', verbose_name='简介')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='(URL)别名')),
                ('title', models.CharField(default='', help_text='title', max_length=255, verbose_name='标题(seo)')),
                ('keywords', models.CharField(default='', help_text='keywords', max_length=255, verbose_name='关键字(seo)')),
                ('description', models.CharField(default='', help_text='description', max_length=255, verbose_name='描述(seo)')),
                ('is_tab', models.BooleanField(default=False, help_text='首页编辑推荐显示', verbose_name='显示在首页')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_album', to='albums.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TabAlbum',
            fields=[
            ],
            options={
                'verbose_name': '推荐专辑',
                'verbose_name_plural': '推荐专辑',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('albums.album',),
        ),
    ]
