# Generated by Django 2.2.2 on 2019-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='push',
            field=models.BooleanField(default=False, help_text='推送给熊掌', verbose_name='推送'),
        ),
        migrations.AddField(
            model_name='category',
            name='push',
            field=models.BooleanField(default=False, help_text='推送给熊掌', verbose_name='推送'),
        ),
    ]
