# Generated by Django 2.2.2 on 2019-08-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20190831_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, default='', help_text='description', max_length=255, verbose_name='描述(seo)'),
        ),
    ]
