# Generated by Django 2.2.2 on 2019-08-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20190828_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabAlbum',
            fields=[
            ],
            options={
                'verbose_name': '推荐专辑',
                'verbose_name_plural': '推荐专辑',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('albums.album',),
        ),
    ]
