# Generated by Django 2.2.2 on 2019-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20190831_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-updated_at',), 'verbose_name': '专辑', 'verbose_name_plural': '专辑'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterField(
            model_name='album',
            name='is_tab',
            field=models.BooleanField(default=False, help_text='首页编辑推荐显示', verbose_name='编辑推荐'),
        ),
    ]
