# Generated by Django 2.2.2 on 2019-08-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20190831_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='info',
            field=models.TextField(verbose_name='简介'),
        ),
    ]
