# Generated by Django 2.2.2 on 2019-09-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_auto_20190831_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show',
            field=models.BooleanField(default=True, help_text='在导航显示', verbose_name='显示'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='排序'),
        ),
    ]
