# Generated by Django 2.2.2 on 2019-09-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_auto_20190926_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort',), 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AddField(
            model_name='category',
            name='mold',
            field=models.CharField(choices=[('Z', '专栏'), ('W', '文章')], default='Z', max_length=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show',
            field=models.BooleanField(default=True, help_text='在导航显示', verbose_name='导航显示'),
        ),
    ]
