# Generated by Django 2.2.2 on 2019-10-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_auto_20190929_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_machine',
            field=models.BooleanField(default=False, help_text='是否采集提交', verbose_name='是否机器提交'),
        ),
    ]
