# Generated by Django 2.2.2 on 2019-08-30 05:52

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='(URL)别名')),
                ('status', models.CharField(choices=[('D', '不公开'), ('P', '公开')], default='D', max_length=1, verbose_name='状态')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('title', models.CharField(default='', help_text='title', max_length=255, verbose_name='标题(seo)')),
                ('keywords', models.CharField(default='', help_text='keywords', max_length=255, verbose_name='关键字(seo)')),
                ('description', models.CharField(default='', help_text='description', max_length=255, verbose_name='描述(seo)')),
                ('is_notice', models.BooleanField(default=False, help_text='不是文章而是站内公告', verbose_name='公告消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('album', models.ManyToManyField(blank=True, related_name='article_album', to='albums.Album', verbose_name='专辑')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='多个标签使用,(英文)隔开', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-updated_at',),
                'index_together': {('status', 'slug')},
            },
        ),
    ]
