# Generated by Django 2.2.2 on 2019-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='push',
            field=models.BooleanField(default=False, help_text='推送给熊掌', verbose_name='推送'),
        ),
    ]
