# Generated by Django 2.2.2 on 2019-08-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, default='', help_text='description', max_length=255, null=True, verbose_name='描述(seo)'),
        ),
    ]
