# Generated by Django 2.2.2 on 2019-08-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('D', '不公开'), ('P', '公开')], db_index=True, default='D', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterIndexTogether(
            name='article',
            index_together={('status', 'slug')},
        ),
    ]
