# Generated by Django 2.2.2 on 2019-09-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190831_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_old',
            field=models.BooleanField(default=True, help_text='是否老数据', verbose_name='是否老数据'),
        ),
    ]
