# Generated by Django 2.2.2 on 2019-08-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190828_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_album', to='albums.Album', verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_notice',
            field=models.BooleanField(default=False, help_text='不是文章而是站内公告', verbose_name='公告消息'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('D', '不公开'), ('P', '公开')], default='D', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
    ]
