# Generated by Django 2.2.2 on 2019-08-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190828_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='article_album', to='albums.Album', verbose_name='专辑'),
        ),
    ]
