# Generated by Django 2.2.2 on 2019-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190918_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datatype',
            field=models.CharField(choices=[('A', '老文章'), ('B', '公告'), ('C', '普通文章')], default='C', max_length=1, verbose_name='数据类型'),
        ),
    ]
