# Generated by Django 2.2.2 on 2019-09-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190918_1235'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='article',
            index_together={('status', 'datatype'), ('status', 'slug', 'datatype')},
        ),
    ]
