# Generated by Django 2.2.2 on 2019-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_auto_20190929_0836'),
        ('articles', '0009_auto_20190918_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='album_article', to='albums.Album', verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='article',
            name='compose',
            field=models.ManyToManyField(blank=True, related_name='compose_article', to='operation.Compose', verbose_name='聚合'),
        ),
    ]
