# Generated by Django 2.2.2 on 2019-09-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20190929_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
