# Generated by Django 2.2.2 on 2019-09-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20190929_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_article', to='albums.Category', verbose_name='所属导航'),
        ),
    ]
