# Generated by Django 2.2.2 on 2019-09-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20190929_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
