# Generated by Django 2.2.2 on 2019-10-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='norm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='来源标识'),
        ),
    ]
